export const motivationalQuotes = [
  "Keep going, you're closer than you think.",
  "One step at a time.",
  "Small progress is still progress.",
  "Every day is a fresh start.",
  "You are capable of amazing things.",
  "Dream big, start small.",
  "Stay focused and never give up.",
  "Push yourself, because no one else will.",
  "Success is no accident.",
  "Believe you can, and you’re halfway there.",
  "You don’t have to be perfect to be amazing.",
  "Do it for your future self.",
  "Be your own hero.",
  "Mistakes are proof that you’re trying.",
  "Trust the process.",
  "Rise above the storm, and you will find the sunshine.",
  "The best is yet to come.",
  "Great things never come from comfort zones.",
  "You’re stronger than you know.",
  "Doubt kills more dreams than failure ever will.",
  "Success doesn’t come from what you do occasionally; it comes from what you do consistently.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Stay positive, work hard, make it happen.",
  "Your only limit is you.",
  "Don't stop until you're proud.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Believe in yourself and all that you are.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Don't wait for opportunity, create it.",
  "Believe in the power of yet.",
  "Success is what happens after you’ve survived all your mistakes.",
  "Don't watch the clock; do what it does. Keep going.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "Don’t be afraid to give up the good to go for the great.",
  "Wake up with determination; go to bed with satisfaction.",
  "Your dreams don’t have an expiration date.",
  "A little progress each day adds up to big results.",
  "Dream it, wish it, do it.",
  "You are never too old to set another goal or to dream a new dream.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Good things come to those who hustle.",
  "Your potential is endless.",
  "If it was easy, everyone would do it.",
  "Don't let yesterday take up too much of today.",
  "Failure is not the opposite of success; it’s part of success.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Make today count.",
  "What defines us is how well we rise after falling.",
  "Don’t quit. Suffer now and live the rest of your life as a champion.",
  "Don’t wait for the perfect moment; take the moment and make it perfect.",
  "Go as far as you can see; when you get there, you’ll be able to see further.",
  "The journey of a thousand miles begins with a single step.",
  "Nothing worth having comes easy.",
  "Strive for progress, not perfection.",
  "Don’t limit your challenges, challenge your limits.",
  "It’s not about being the best; it’s about being better than you were yesterday.",
  "Work hard in silence, let your success be the noise.",
  "You are stronger than you think.",
  "The only way to do great work is to love what you do.",
  "Fall seven times, stand up eight.",
  "Take a deep breath and start again.",
  "Push harder than yesterday if you want a different tomorrow.",
  "Focus on the step in front of you, not the whole staircase.",
  "Great things take time.",
  "Stay patient and trust your journey.",
  "Success is a journey, not a destination.",
  "You get what you work for, not what you wish for.",
  "The best view comes after the hardest climb.",
  "You didn’t come this far only to come this far.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "You can’t go back and change the beginning, but you can start where you are and change the ending.",
  "Your passion is waiting for your courage to catch up.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Every day may not be good, but there’s something good in every day.",
  "Focus on your goals, not your fears.",
  "Set goals. Stay quiet about them. Smash them.",
  "Don't downgrade your dream just to fit your reality.",
  "Stay positive. Stay fighting. Stay brave.",
  "Difficult roads often lead to beautiful destinations.",
  "The secret of getting ahead is getting started.",
  "Dream big and dare to fail.",
  "Be the reason someone smiles today.",
  "With the new day comes new strength.",
  "Don’t let your fear decide your future.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Good things come to those who believe.",
  "Life is 10% what happens to you and 90% how you react to it.",
  "Hustle until your haters ask if you’re hiring.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Today is another chance to get it right.",
  "You are exactly where you need to be.",
  "Be stronger than your excuses.",
  "Make yourself proud.",
  "You’ll never be ready; just start.",
  "Every accomplishment starts with the decision to try.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Keep your dreams alive.",
  "Progress over perfection.",
  "Stop wishing, start doing.",
  "Fall in love with the process, and the results will come.",
  "You are capable of more than you know.",
  "There’s no traffic on the extra mile.",
  "If it doesn’t challenge you, it doesn’t change you.",
  "Do something today that your future self will thank you for.",
  "Focus on being productive instead of busy.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "Success is not for the lazy.",
  "The expert in anything was once a beginner.",
  "The difference between who you are and who you want to be is what you do.",
  "Make your life a masterpiece.",
  "Your vibe attracts your tribe.",
  "Every champion was once a contender that refused to give up.",
  "Turn your wounds into wisdom.",
  "Stay hungry, stay foolish.",
  "Every day is an opportunity to improve.",
  "Nothing can dim the light that shines from within.",
  "Do what you can with what you have, where you are.",
  "Never regret anything that made you smile.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Do what makes you happy.",
  "The best revenge is massive success.",
  "Believe in your infinite potential.",
  "Winners are not people who never fail, but people who never quit.",
  "Action is the foundational key to all success.",
  "Live less out of habit and more out of intent.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "It always seems impossible until it’s done.",
  "Start where you are. Use what you have. Do what you can.",
  "The struggle you’re in today is developing the strength you need for tomorrow.",
  "Don’t look back—you’re not going that way.",
  "Set goals, crush them, and repeat.",
  "Failure is the opportunity to begin again more intelligently.",
  "Do it now. Sometimes ‘later’ becomes ‘never.’",
  "Be proud of how hard you’re working.",
  "Challenges are what make life interesting.",
  "Don’t wish for it; work for it.",
  "Your story is far from over.",
  "Be so good they can’t ignore you.",
  "The best way to predict the future is to create it.",
  "Keep your head up, and your heart strong.",
  "You are more resilient than you think.",
  "Every setback is a setup for a comeback.",
  "Your life is as good as your mindset.",
  "Success is a series of small wins.",
  "Stay humble, work hard, be kind.",
  "Don’t talk, just act.",
  "There is no substitute for hard work.",
  "What you do today can improve all your tomorrows.",
  "The journey is just as important as the destination.",
  "You don’t have to have it all figured out to move forward.",
  "Push yourself because no one else is going to do it for you.",
  "Believe in yourself even when no one else does.",
  "The best way out is always through.",
  "Keep grinding; your day will come.",
  "It’s never too late to be what you might have been.",
  "Don’t be afraid to give yourself everything you’ve ever wanted in life.",
  "Success is built on sacrifice.",
  "You’re stronger than your excuses.",
  "Choose courage over comfort.",
  "Don’t dream of success; work for it.",
  "Live each day as if your life had just begun.",
  "The biggest risk is not taking any risk.",
  "The first step is you have to say that you can.",
  "The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience."
];
